/**
 * Session export to Markdown and JSON formats.
 */

import { SummaryState, ContextEntry } from './pipeline/summary-engine'

export interface SessionData {
  startTime: number
  endTime: number
  transcripts: Array<{
    id: string
    timestamp: number
    text: string
    start: number
    end: number
  }>
  visualNotes: Array<{
    id: string
    timestamp: number
    text: string
  }>
  summary: SummaryState | null
  contextBuffer: ContextEntry[]
}

function formatDuration(ms: number): string {
  const totalSec = Math.floor(ms / 1000)
  const h = Math.floor(totalSec / 3600)
  const m = Math.floor((totalSec % 3600) / 60)
  const s = totalSec % 60
  if (h > 0) return `${h}h ${m}m ${s}s`
  return `${m}m ${s}s`
}

function formatTimestamp(ts: number, startTime: number): string {
  const elapsed = Math.floor((ts - startTime) / 1000)
  const m = Math.floor(elapsed / 60).toString().padStart(2, '0')
  const s = (elapsed % 60).toString().padStart(2, '0')
  return `${m}:${s}`
}

export function exportMarkdown(session: SessionData): string {
  const date = new Date(session.startTime)
  const duration = formatDuration(session.endTime - session.startTime)
  
  let md = `# Godeye Session Summary\n\n`
  md += `**Date:** ${date.toLocaleDateString()} ${date.toLocaleTimeString()}\n`
  md += `**Duration:** ${duration}\n\n`
  md += `---\n\n`

  // Summary
  if (session.summary) {
    if (session.summary.documentSummary) {
      md += `## 📄 Document Summary\n\n`
      md += `${session.summary.documentSummary}\n\n`
    }

    if (session.summary.statements && session.summary.statements.length > 0) {
      md += `### 📝 Key Statements\n\n`
      for (const d of session.summary.statements) {
        md += `- ${d}\n`
      }
      md += `\n`
    }

    if (session.summary.questions && session.summary.questions.length > 0) {
      md += `### ❓ Questions Raised\n\n`
      for (const q of session.summary.questions) {
        md += `- ${q}\n`
      }
      md += `\n`
    }

    if (session.summary.followUpQuestions && session.summary.followUpQuestions.length > 0) {
      md += `### 💡 Follow-Up Questions\n\n`
      for (const fq of session.summary.followUpQuestions) {
        md += `- **${fq.question}**\n  *${fq.answer ? fq.answer : 'Unanswered'}*\n`
      }
      md += `\n`
    }
  }

  md += `---\n\n`

  // Transcript
  md += `## 📝 Full Transcript\n\n`
  if (session.transcripts.length === 0) {
    md += `*No transcript entries recorded*\n\n`
  } else {
    for (const entry of session.transcripts) {
      const time = formatTimestamp(entry.timestamp, session.startTime)
      md += `**[${time}]** ${entry.text}\n\n`
    }
  }

  md += `---\n\n`

  // Visual Notes
  md += `## 👁 Visual Notes\n\n`
  if (session.visualNotes.length === 0) {
    md += `*No visual notes captured*\n\n`
  } else {
    for (const note of session.visualNotes) {
      const time = formatTimestamp(note.timestamp, session.startTime)
      md += `**[${time}]** ${note.text.substring(0, 200)}${note.text.length > 200 ? '...' : ''}\n\n`
    }
  }

  md += `---\n\n`
  md += `*Generated by Godeye — Context-Aware Desktop Observer*\n`

  return md
}

export function exportJSON(session: SessionData): string {
  const exportData = {
    metadata: {
      generator: 'Godeye',
      version: '1.0.0',
      startTime: new Date(session.startTime).toISOString(),
      endTime: new Date(session.endTime).toISOString(),
      durationMs: session.endTime - session.startTime
    },
    summary: session.summary,
    timeline: [
      ...session.transcripts.map(t => ({
        type: 'transcript' as const,
        timestamp: t.timestamp,
        relativeMs: t.timestamp - session.startTime,
        content: t.text,
        start: t.start,
        end: t.end
      })),
      ...session.visualNotes.map(v => ({
        type: 'visual' as const,
        timestamp: v.timestamp,
        relativeMs: v.timestamp - session.startTime,
        content: v.text
      }))
    ].sort((a, b) => a.timestamp - b.timestamp)
  }

  return JSON.stringify(exportData, null, 2)
}
